[kube_master]
master1 ansible_host=192.168.9.41

[kube_node]
worker1 ansible_host=192.168.9.42
worker2 ansible_host=192.168.9.43

[k8s_cluster:children]
kube_master
kube_node

[all:vars]
ansible_user=root
# 如果使用密码验证，请取消下面注释并填入密码
ansible_ssh_pass=2220
# ansible_become_pass=YOUR_SUDO_PASSWORD
# 如果使用特定的私钥：
# ansible_ssh_private_key_file=~/.ssh/id_rsa
